Question 1

In [ ]:
import numpy as np

arry=np.arange(2,51,3)
print(arry)

[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47 50]


Question 2

In [ ]:
import numpy as np
list_1 =[int(input()) for i in range(5)]
list_2 =[int(input()) for j in range(5)]
arr=np.array(list_1+list_2)
print(" ")
print(" ")
print("Afetr concatenating both input lists ")
print(arr)
print(" ")
print(" ")
print("After sorting the sorted the array")
arr=np.array(sorted(list_1+list_2))
print(arr)

Question 3

In [ ]:
import numpy as np
arr=np.array([int(i) for i in range(1,13) ])
arr.resize(2,2,3)
print("Size of array: ",arr.size)
print("Dimenssion of array: ",arr.ndim)


Size of array:  12
Dimenssion of array:  3


Question 4

converting 1D array to 2D using "newaxis" and "expand_dims"

In [15]:
import numpy as np 
arr= np.array([2,3,4]) #1D array
arr_2=arr[np.newaxis, :] #2D array
arr_3= np.expand_dims(arr, axis=0)

print("dimenssion of arr: ",arr.ndim)
print("'Conversion of 1D array to 2D using newaxis' ")
print("Dimenssion of arr_2: ",arr_2.ndim)
print("'Conversion of 1D array to 2D using expand_dims'")
print("Dimenssion of arr_3: ",arr_3.ndim)


dimenssion of arr:  1
'Conversion of 1D array to 2D using newaxis' 
Dimenssion of arr_2:  2
'Conversion of 1D array to 2D using expand_dims'
Dimenssion of arr_3:  2


Question 5

In [21]:
import numpy as np 
a=np.array([1,2,3,4,5])
b=np.array([6,7,8,9,10])
vertical=np.vstack((a,b))
print("Vstack \n",vertical) 
horizontal=np.hstack((a,b))
print("\n\nHtack\n",horizontal)

Vstack 
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


Htack
 [ 1  2  3  4  5  6  7  8  9 10]


Question 6

In [22]:
import numpy as np
arr=np.array([3,5,10,9,6,8,10,5,2,4,2,23,45,23,6,9,10])
#np.unique gives unique vales in given array 
# return_counts inside the np.unique() gives the counts of the unique items
unique_val,count=np.unique(arr,return_counts=True) 

print("Unique value in array:\n",unique_val)
print("\n occurance of unique values in array:\n",count)

Unique value in array:
 [ 2  3  4  5  6  8  9 10 23 45]

 occurance of unique values in array:
 [2 1 1 2 2 1 2 3 2 1]
